os: linux

dist: bionic

language: python

python:
- '3.6'
- '3.8'

env:
  matrix:
  - DJANGO_VERSION=2.2.*
  - DJANGO_VERSION=3.1.*
  - DJANGO_VERSION=dev

services:
- postgresql

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10-postgis-2.4

stages:
- lint
- test
- deploy

install:
- sudo apt-get -y install libproj-dev binutils gdal-bin libgdal-dev
- pip install .[dev,mapbox,postgis]
- pip install codecov
- if [[ $DJANGO_VERSION == dev ]]; then
  pip install -e git+https://github.com/django/django@master#egg=django;
  else
  pip install Django==$DJANGO_VERSION -U; fi

before_script:
- psql -c "CREATE USER travis_ci_test WITH ENCRYPTED PASSWORD 'travis_ci_test';" -U
  postgres
- psql -c "ALTER USER travis_ci_test WITH SUPERUSER;" -U postgres
- psql -c 'CREATE DATABASE travis_ci_test WITH OWNER travis_ci_test;' -U postgres
- psql -d travis_ci_test -c 'CREATE EXTENSION postgis;'

after_failure:
- pip freeze

script:
- coverage run ./manage.py test

after_success:
  - codecov

jobs:
  allow_failures:
    - env: DJANGO_VERSION=dev

  include:
  - stage: lint
    install:
    - pip install flake8
    before_script: skip
    script:
    - flake8 vectortiles test_vectortiles
    after_success: skip

  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    deploy:
      skip_cleanup: true
      provider: pypi
      username: __token__
      password:
        secure: "Ll0sRBWObhd/ec8dZK+YnNiwreMClYwJsuFpWzebZJFNuFwlrT9UzLflvsdCq7BXM7oQFY+jwoObSYZB2uyVQYlqui9AzG/5mu0XsSs3r0ZTkrRxJXOJ8q9n9qeb2ff707VTzoOO6u85FI8x+q4otpOIxTj/TnMxDAk1GXFsVOR4OiP6akYRiKS8QwyLVvY9QuDxzHqsozDWU4UaQNjlGiMtrQwm3pRRP1DEC6M36BWhce+SMB7Du35o1I3RdYuUPsMXv5I4q+BeC8cmYPsPgu9n0FhMbNQjVYPzcZgmaWMUCL3S5DvmD/V1jeinj4rfgHsxA1nxi+x9jxFixBdI7geek5JbRtfDJV10EYmLDsDA4GMbo02DYR5aUpWuSFl4+X5inpTQLWIXZrYcXFfp8DnWkukKRRNfkSXMK34EGbHZxuzc8qh8FYzTFyh/iFfQdPR8PlSjLkEHyrnYzGNB8rGjddxkoXHw5Y3A+h70+tl460B5HcigfYR4Y2ymhQFBPFJ/VWUCTxwxlbxgNEU+0AEwCFet+ZF9NNNodSOG14xqJSEF15GRiX/6MgiV1MP2snvU89CeAEC+3ieDWvDdZd35/daVzyryHFi4+Xtt4OUYcrLyjDPF6DmBWRx4DDZ3vVD85icUaPF9/Srr+8zB/wwJMKq8TdxJqbQvHznK2zA="
      on:
        tags: true
